### ISSUE TITLE
Final Report Database

### ISSUE THREAD

**Issue by ZheLiu08** [DS4B-ANU/help#4]
• Link to the dataset and  explain what it is: 
- https://www.who.int/data/gho/data/themes/mortality-and-global-health-estimates
- This database is WHO's Global Health Estimates, providing the most recent data on global causes of death and disability by WHO region and country, age, sex, and income group.

• Summary of the structure of the database and what it contains:
This database contains: 
- "Life expectancy and healthy life expectancy"
- "Global health estimates: Leading causes of death "
- "Global health estimates: Leading causes of DALYs" and other data sets

• Why this dataset is both biological and interesting:
"Death" is a problem that afflicts all of us, and exploring life expectancy and the leading causes of human death helps us unravel the mystery of "death"

• Summary of the types of questions and/or aims that could be addressed using this dataset (perhaps in combination with other approved datasets) ：
- Healthy life expectancy and Life expectancy in different regions can be explored on a global scale.
- The main causes of death and mortality levels among children could be explored.

**Comment by DS4B-ANU** [comment]
@ZheLiu08, since your dataset is already on the approved list, this post is unnecessary. Please go ahead and start filling in your report.
